title: Kishan Shah
logo: headshot.jpg
description: Passionate about using data to drive business solutions and empower data-driven decision-making for strategic growth.
# show_downloads: true
theme: jekyll-theme-minimal
